
package org.lugubria.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://services.lugubria.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param userId
     * @return
     *     returns org.lugubria.services.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://services.lugubria.org/", className = "org.lugubria.services.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://services.lugubria.org/", className = "org.lugubria.services.GetUserByIdResponse")
    public User getUserById(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param login
     * @param password
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userValid", targetNamespace = "http://services.lugubria.org/", className = "org.lugubria.services.UserValid")
    @ResponseWrapper(localName = "userValidResponse", targetNamespace = "http://services.lugubria.org/", className = "org.lugubria.services.UserValidResponse")
    public boolean userValid(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
